# Generated by Django 4.1.1 on 2022-09-16 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("x7_local_net", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddrIpModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name="AddrMacModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mac", models.CharField(blank=True, default="", max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name="devicemodel",
            name="mac",
        ),
        migrations.AddField(
            model_name="devicemodel",
            name="mac_set",
            field=models.ManyToManyField(
                related_name="device_set", to="x7_local_net.addrmacmodel"
            ),
        ),
        migrations.AlterField(
            model_name="arpmodel",
            name="ip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="x7_local_net.addripmodel",
            ),
        ),
        migrations.AlterField(
            model_name="arpmodel",
            name="mac",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="x7_local_net.addrmacmodel",
            ),
        ),
    ]
