# Generated by Django 4.1.1 on 2022-09-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("x7_local_net", "0003_devicemodel_ip_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicemodel",
            name="offline",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="servermodel",
            name="offline",
            field=models.BooleanField(default=False),
        ),
    ]
