# Generated by Django 4.1.1 on 2022-09-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("x7_local_nameserver", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordmodel",
            name="name",
            field=models.CharField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recordmodel",
            name="value",
            field=models.TextField(),
        ),
    ]
