# Generated by Django 4.1.1 on 2022-09-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("x7_local_nameserver", "0002_recordmodel_name_alter_recordmodel_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordmodel",
            name="ttl",
            field=models.PositiveIntegerField(default=600),
        ),
    ]
